name: Notify Movement Form Response

on:
  push:
    paths:
      - 'movement_responses.json'

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check secrets and test bot token
        run: |
          echo "🔧 Checking configuration..."
          echo "📊 Bot token configured: ${{ secrets.TELEGRAM_BOT_TOKEN != '' }}"
          echo "📊 Admin ID configured: ${{ secrets.BOT_ADMIN_ID != '' }}"
          
          echo "🧪 Testing bot token..."
          TEST_RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getMe")
          echo "🧪 Bot test response: $TEST_RESPONSE"
          
          if echo "$TEST_RESPONSE" | jq -e '.ok == true' > /dev/null; then
            echo "✅ Bot token is valid!"
            BOT_USERNAME=$(echo "$TEST_RESPONSE" | jq -r '.result.username')
            echo "🤖 Bot username: @$BOT_USERNAME"
          else
            echo "❌ Bot token is invalid!"
            exit 1
          fi
        
      - name: Parse movement form responses
        id: parse
        run: |
          echo "🔍 Parsing movement_responses.json..."
          
          if [ ! -f "movement_responses.json" ] || [ ! -s "movement_responses.json" ]; then
            echo "❌ movement_responses.json not found or empty"
            exit 1
          fi
          
          echo "📄 Current movement_responses.json content:"
          cat movement_responses.json
          
          NEW_USER_ID=$(jq -r '.[-1].user_id' movement_responses.json)
          NEW_USERNAME=$(jq -r '.[-1].responses.username // "нет"' movement_responses.json)
          NEW_REFERRAL=$(jq -r '.[-1].responses.referral // "нет"' movement_responses.json)
          NEW_FIRST_NAME=$(jq -r '.[-1].responses.Имя // "не указано"' movement_responses.json)
          
          if [ "$NEW_USER_ID" = "null" ] || [ -z "$NEW_USER_ID" ]; then
            echo "❌ Could not extract telegram_id from movement_responses.json"
            echo "📋 Available data:"
            jq '.' movement_responses.json
            exit 1
          fi
          
          echo "user_id=${NEW_USER_ID}" >> $GITHUB_ENV
          echo "username=${NEW_USERNAME}" >> $GITHUB_ENV
          echo "referral=${NEW_REFERRAL}" >> $GITHUB_ENV
          echo "first_name=${NEW_FIRST_NAME}" >> $GITHUB_ENV
          echo "✅ Found new movement form response from user: $NEW_USER_ID (@$NEW_USERNAME)"
        
      - name: Send thank you message to user
        run: |
          echo "📤 Sending thank you message to user ${user_id}..."
          
          RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -H "Content-Type: application/json" -d "{\"chat_id\": \"${user_id}\", \"text\": \"✅ Спасибо за заявку на тариф «Движение»! Мы рассмотрим вашу заявку и свяжемся с вами в ближайшее время. Если у вас есть вопросы, пишите в поддержку.\"}")
          
          echo "📡 User notification response: $RESPONSE"
          
          if echo "$RESPONSE" | jq -e '.ok == true' > /dev/null; then
            echo "✅ User notification sent successfully!"
            echo "user_notified=true" >> $GITHUB_ENV
          else
            echo "❌ Failed to send user notification"
            echo "user_notified=false" >> $GITHUB_ENV
            echo "🔍 Error details: $RESPONSE"
          fi

      - name: Send admin info message
        run: |
          echo "📤 Sending admin info message..."
          
          ADMIN_MESSAGE="📋 +1 заявка на тариф «Движение»! \n👤 <b>Пользователь:</b> ${first_name} \n🆔 <b>ID:</b> ${user_id} \n📱 <b>Username:</b> @${username} \n🔗 <b>Реферал:</b> ${referral} \n✅ Форма заполнена и отправлена"
          
          ADMIN_INFO_RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{
              \"chat_id\": \"${{ secrets.BOT_ADMIN_ID }}\", 
              \"text\": \"${ADMIN_MESSAGE}\",
              \"parse_mode\": \"HTML\"
            }")
          
          echo "📡 Admin info response: $ADMIN_INFO_RESPONSE"
          
          if echo "$ADMIN_INFO_RESPONSE" | jq -e '.ok == true' > /dev/null; then
            echo "✅ Admin info sent successfully!"
            echo "admin_notified=true" >> $GITHUB_ENV
          else
            echo "❌ Failed to send admin info"
            echo "admin_notified=false" >> $GITHUB_ENV
            echo "🔍 Error details: $ADMIN_INFO_RESPONSE"
          fi

      - name: Final status report
        run: |
          echo "🎯 Final Status Report:"
          echo "👤 User ID: ${user_id}"
          echo "📱 Username: @${username}"
          echo "🔗 Referral: ${referral}"
          echo "📤 User notified: ${user_notified:-false}"
          echo "👨‍💼 Admin notified: ${admin_notified:-false}"
          
          if [ "${user_notified:-false}" = "true" ] && [ "${admin_notified:-false}" = "true" ]; then
            echo "🎉 All operations completed successfully!"
          else
            echo "⚠️ Some operations failed"
            exit 1
          fi
